name = "Ruins of the Ancients MULTIPLAYER"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81aca7b6c71fc326d9423885a9a2c09eda9fd7a8c424cd0fb7d0b28cae982c2f"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
