name = "Ruins of the Ancients MULTIPLAYER"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd0ae86d7d12f6ce7beacd0c000834efadb20be321f1d996b84149bf78ed0804"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
