name = "Advanced Rocketry"
filename = "AdvancedRocketry-1.12.2-1.7.0-239-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3243/269/AdvancedRocketry-1.12.2-1.7.0-239-universal.jar"
hash-format = "murmur2"
hash = "1741729410"

[update]
[update.curseforge]
file-id = 3243269
project-id = 236542
release-channel = "beta"
