name = "Advanced Rocketry"
filename = "AdvancedRocketry-1.12.2-2.0.0-248-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3305/757/AdvancedRocketry-1.12.2-2.0.0-248-universal.jar"
hash-format = "murmur2"
hash = "2836267918"

[update]
[update.curseforge]
file-id = 3305757
project-id = 236542
release-channel = "beta"
