name = "Advanced Rocketry"
filename = "AdvancedRocketry-1.12.2-1.7.0-240-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3247/375/AdvancedRocketry-1.12.2-1.7.0-240-universal.jar"
hash-format = "murmur2"
hash = "3310838760"

[update]
[update.curseforge]
file-id = 3247375
project-id = 236542
release-channel = "beta"
