name = "Advanced Rocketry"
filename = "AdvancedRocketry-1.12.2-2.0.0-247-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3303/400/AdvancedRocketry-1.12.2-2.0.0-247-universal.jar"
hash-format = "murmur2"
hash = "3903907220"

[update]
[update.curseforge]
file-id = 3303400
project-id = 236542
release-channel = "beta"
