name = "Advanced Rocketry"
filename = "AdvancedRocketry-1.12.2-2.0.0-250-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3347/618/AdvancedRocketry-1.12.2-2.0.0-250-universal.jar"
hash-format = "murmur2"
hash = "8321123"

[update]
[update.curseforge]
file-id = 3347618
project-id = 236542
release-channel = "beta"
