name = "Advanced Rocketry"
filename = "AdvancedRocketry-1.12.2-1.7.0-237-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3188/352/AdvancedRocketry-1.12.2-1.7.0-237-universal.jar"
hash-format = "murmur2"
hash = "2419666791"

[update]
[update.curseforge]
file-id = 3188352
project-id = 236542
release-channel = "beta"
