name = "CraftTweaker"
filename = "CraftTweaker2-1.12-4.1.20.648.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3348/523/CraftTweaker2-1.12-4.1.20.648.jar"
hash-format = "murmur2"
hash = "1403672803"

[update]
[update.curseforge]
file-id = 3348523
project-id = 239197
release-channel = "beta"
