name = "CraftTweaker"
filename = "CraftTweaker2-1.12-4.1.20.635.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3276/288/CraftTweaker2-1.12-4.1.20.635.jar"
hash-format = "murmur2"
hash = "855014837"

[update]
[update.curseforge]
file-id = 3276288
project-id = 239197
release-channel = "beta"
