name = "CraftTweaker"
filename = "CraftTweaker2-1.12-4.1.20.618.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3202/907/CraftTweaker2-1.12-4.1.20.618.jar"
hash-format = "murmur2"
hash = "1829841549"

[update]
[update.curseforge]
file-id = 3202907
project-id = 239197
release-channel = "beta"
