name = "CraftTweaker"
filename = "CraftTweaker2-1.12-4.1.20.624.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3218/125/CraftTweaker2-1.12-4.1.20.624.jar"
hash-format = "murmur2"
hash = "2191589084"

[update]
[update.curseforge]
file-id = 3218125
project-id = 239197
release-channel = "beta"
