name = "CraftTweaker"
filename = "CraftTweaker2-1.12-4.1.20.633.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3266/764/CraftTweaker2-1.12-4.1.20.633.jar"
hash-format = "murmur2"
hash = "3929982362"

[update]
[update.curseforge]
file-id = 3266764
project-id = 239197
release-channel = "beta"
