name = "CraftTweaker"
filename = "CraftTweaker2-1.12-4.1.20.634.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3268/209/CraftTweaker2-1.12-4.1.20.634.jar"
hash-format = "murmur2"
hash = "2548097075"

[update]
[update.curseforge]
file-id = 3268209
project-id = 239197
release-channel = "beta"
