name = "CreativeCore"
filename = "CreativeCore_v1.10.16_mc1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2968/171/CreativeCore_v1.10.16_mc1.12.2.jar"
hash-format = "murmur2"
hash = "958672097"
