name = "Draconic Additions"
filename = "Draconic-Additions-1.12.2-1.16.3.43-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3290/481/Draconic-Additions-1.12.2-1.16.3.43-universal.jar"
hash-format = "murmur2"
hash = "3089744458"

[update]
[update.curseforge]
file-id = 3290481
project-id = 314515
release-channel = "beta"
