name = "Draconic Additions"
filename = "Draconic-Additions-1.12.2-1.16.4.44-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3323/992/Draconic-Additions-1.12.2-1.16.4.44-universal.jar"
hash-format = "murmur2"
hash = "3572261682"

[update]
[update.curseforge]
file-id = 3323992
project-id = 314515
release-channel = "beta"
