name = "DynmapForge"
filename = "Dynmap-3.1-forge-1.12.2.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3242/285/Dynmap-3.1-forge-1.12.2.jar"
hash-format = "murmur2"
hash = "1216538094"

[update]
[update.curseforge]
file-id = 3242285
project-id = 59433
release-channel = "beta"
