name = "Just Enough Calculation"
filename = "JustEnoughCalculation-1.12.2-3.2.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3201/179/JustEnoughCalculation-1.12.2-3.2.5.jar"
hash-format = "murmur2"
hash = "2825693595"

[update]
[update.curseforge]
file-id = 3201179
project-id = 242223
release-channel = "beta"
