name = "Just Enough Calculation"
filename = "JustEnoughCalculation-1.12.2-3.2.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3293/954/JustEnoughCalculation-1.12.2-3.2.6.jar"
hash-format = "murmur2"
hash = "1112125870"

[update]
[update.curseforge]
file-id = 3293954
project-id = 242223
release-channel = "beta"
