name = "LibVulpes"
filename = "LibVulpes-1.12.2-0.4.2-83-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3261/667/LibVulpes-1.12.2-0.4.2-83-universal.jar"
hash-format = "murmur2"
hash = "1555213411"

[update]
[update.curseforge]
file-id = 3261667
project-id = 236541
release-channel = "beta"
