name = "Mod Name Tooltip"
filename = "modnametooltip_1.12.2-1.10.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/2739/582/modnametooltip_1.12.2-1.10.1.jar"
hash-format = "murmur2"
hash = "563839039"

[update]
[update.curseforge]
file-id = 2739582
project-id = 238747
release-channel = "beta"
