name = "Reborn Core"
filename = "RebornCore-1.12.2-3.19.5-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3330/308/RebornCore-1.12.2-3.19.5-universal.jar"
hash-format = "murmur2"
hash = "595501837"

[update]
[update.curseforge]
file-id = 3330308
project-id = 237903
release-channel = "beta"
