name = "UniDict"
filename = "UniDict-1.12.2-3.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3201/828/UniDict-1.12.2-3.0.6.jar"
hash-format = "murmur2"
hash = "3950774697"

[update]
[update.curseforge]
file-id = 3201828
project-id = 244258
release-channel = "beta"
