name = "UniDict"
filename = "UniDict-1.12.2-3.0.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3240/606/UniDict-1.12.2-3.0.7.jar"
hash-format = "murmur2"
hash = "32223528"

[update]
[update.curseforge]
file-id = 3240606
project-id = 244258
release-channel = "beta"
